config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  mount Lockup::Engine, at: '/lockup'

  if ENV['HEROKUAPP_URL'].present? && ENV['PUBLIC_URL'].present?
    constraints(host: /#{ENV['HEROKUAPP_URL']}/) do
      match "/(*path)", to: redirect { |params, req| "//#{ENV['PUBLIC_URL']}/#{params[:path]}" }, via: [:get, :post]
    end
  end

  root to: "home#index"

  devise_for :users,
    skip: :registrations

  resources :choirs
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :choirs
end

app/models/choir.rb
require 'uri'

class Choir < ActiveRecord::Base

  # associations
  belongs_to :category

  # validations
  validates :name,
            presence: true,
            uniqueness: true,
            length: { minimum: 3 }
  validates :zipcode,
            presence: true,
            numericality: { only_integer: true },
            inclusion: { in: 10115..14199, message: "nur Berliner PLZ" }
  validates :website,
            format: {with: /\A#{URI::regexp}\z/}, if: :website_changed?
  validates :category, presence: true
  validates :street_name, presence: true

  # scopes
  default_scope { order('name ASC') }

  # avatar upload
  attr_accessor :image
  mount_uploader :image, ImageUploader

  # callbacks
  after_create :send_approve_mail
  after_validation :geocode, if: :full_address_changed?

  # geocoding address
  geocoded_by :full_address

  def full_address
    [street_name, house_no, zipcode, city, country].compact.join(', ')
  end

  def send_approve_mail
    ApplicationMailer.new_choir_needs_approval(self).deliver_now!
  end

  def as_indexed_json(options={})
    as_json(
      only: [:name, :category, :zipcode]
    )
  end

  private

  def full_address_changed?
    :street_name_changed? || :house_no_changed? || :zipcode_changed?
  end

  def website_changed?
    :website_changed? if self.website.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      unless current_user && access_whitelist
        redirect_to root_url, alert: 'Not authorized.'
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    private

    def access_whitelist
      current_user.try(:admin?)
    end
  end
end

app/controllers/admin/categories_controller.rb
module Admin
  class CategoriesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Category.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Category.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/choirs_controller.rb
module Admin
  class ChoirsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Choir.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Choir.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/choirs_controller.rb
class ChoirsController < ApplicationController
  respond_to :html, :js

  # POST /choirs
  # POST /choirs.json
  def create
    @choir = Choir.new(choir_params)

    respond_to do |format|
      if @choir.save
        format.html { redirect_to root_path, notice: 'Vielen Dank! Dein Chor wird nach einer Überprüfung zur Karte hinzugefügt.' }
        format.json { render :show, status: :created, location: @choir }
        format.js { render action: 'create_suc'}
      else
        format.html { render action: :new }
        format.json { render json: @choir.errors, status: :unprocessable_entity }
        format.js { render action: 'create_fail' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_choir
      @choir = Choir.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def choir_params
      params
        .require(:choir)
        .permit(:name,
                :location_name,
                :street_name,
                :category_id,
                :house_no,
                :zipcode,
                :city,
                :country,
                :website,
                :latitude,
                :longitude,
                :image,
                :approved)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @choirs = Choir.all.where(approved: true)
    @categories = Category.all.order(:name)
  end

end

app/views/choirs/_form.html.erb
<%= simple_form_for @choir, remote: true, authenticity_token: true, html: {multipart: true, class: 'form-horizontal'} do |f| %>
  <% if @choir.errors.any? %>
    <div id="error_explanation">
      <h3><%= t 'simple_form.error_notification.default_message', errors: @choir.errors.count %></h3>
    </div>
  <% end %>

  <!-- überprüft checkbox -->
  <% if user_signed_in? %>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-5">
        <%= f.input :approved, label: "Überprüfen" %>
      </div>
    </div>
  <% end %>

  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-1">
      <!-- choir icon -->
      <div class="form-group">
        <div class="row">
          <div class="col-xs-12">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 150px; height: 150px;">
                <img src="<%= image_url('logo_gray_100.png')%>" style="padding-top: 25px; padding-bottom: 25px;" alt="...">
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail"></div>
              <div>
                <span class="btn btn-primary btn-file">
                  <span class="fileinput-new">Logo hochladen</span>
                  <span class="fileinput-exists">Ändern</span>
                  <input type="file" name="choir[image]" id="choir_image">
                </span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Löschen</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- choir name -->
    <div class="col-xs-12 col-sm-6">
      <div class="row">
        <div class="col-xs-12">
          <%= f.input :name, label: false, placeholder: '* Name des Chores', required: true %>
        </div>
      </div>

      <!-- choir website -->
      <div class="row">
        <div class="col-xs-12">
          <%= f.input :website, type: 'url', label: false, placeholder: 'Website: http://...', required: true %>
        </div>
      </div>

      <!-- choir category -->
      <div class="row">
        <div class="col-xs-12">
          <%= f.association :category, label: false, :include_blank => false, required: true %>
        </div>
      </div>

      <!-- choir location -->
      <div class="row">
        <div class="col-xs-12">
          <%= f.input :location_name, label: false, placeholder: 'Probenort' %>
        </div>
        <div class="col-xs-9">
          <%= f.input :street_name, label: false, placeholder: '* Straße', required: true %>
        </div>
        <div class="col-xs-3">
          <%= f.input :house_no, label: false, placeholder: 'Nr.' %>
        </div>
        <div class="col-xs-6">
          <%= f.input :zipcode, type: 'number', label: false, placeholder: '* PLZ', required: true %>
        </div>
        <div class="col-xs-6">
          <%= f.input :city, label: false, disabled: true, placeholder: 'Stadt' %>
        </div>
      </div>
    </div>
  </div>

  <!-- submit -->
  <div class="row">
    <div class="text-center">
      <%= f.submit 'Verschicken', class: 'btn btn-primary btn-round', id: 'add-choir' %>
    </div>
  </div>
<% end %>

app/views/choirs/create_fail.js.erb
$('#add-me-form').html("<%= j render 'choirs/form', choir: @choir %>")

app/views/choirs/create_suc.js.erb
$('#add-me-title').html("Vielen Dank!</br> Dein Chor wird nach einer kurzen Überprüfung hinzugefügt.");
$('#add-me-form').html("")

app/views/fields/icon_field/_form.html.erb
<%= f.label field.attribute %>

<% if field.url.present? %>
  <%= image_tag field.url %>
<% else %>
  <%= f.file_field field.attribute %>
<% end %>

app/views/fields/icon_field/_index.html.erb
<%= image_tag field.url %>

app/views/fields/icon_field/_show.html.erb
<%= image_tag field.url %>

app/views/home/_about.html.erb
<h2>Über diese Seite</h2>

<div class="text-left">
  <p>Als ich nach einer kurzen Pause vom Singen wieder nach einem neuen Chor suchte, musste ich feststellen, dass es keine gute Webseite mit einem Überblick aller Berliner Chöre gab. </p>

  <p>So entstand die Idee, die Chöre Berlins zu kartographieren.</p>

  <p>Die Webseite ist in Ruby on Rails und Javascript implementiert, unter Verwendung einer PostgreSQL Datenbank. Die Bereitstellung der Seite erfolgt über Heroku.</p>

  <p>Beim Design der Seite wurde auf Responsiveness geachtet und dafür <a href="http://getbootstrap.com/" target="_blank>">Bootstrap 3</a> und <a href="http://leafletjs.com/" target="_blank">Leaflet.js</a> verwendet.</p>

  <p>Zur Generierung der Karte wurden die <a href="http://download.geofabrik.de/europe/germany/berlin.html" target="_blank">OSM Daten von Berlin</a>, das Programm <a href="https://www.mapbox.com/tilemill/" target="_blank">TileMill</a> und Aaron Lidman's <a href="https://github.com/aaronlidman/Toner-for-Tilemill" target="_blank"><em>Toner for TileMill</em></a> Style verwendet. Ich habe <a href="http://zfhui.de/blag/?p=2673" target="_blank">hier</a> beschrieben wie ich die Karte gebaut habe.</p>

  <p>Der Source-Code steht unter MIT Lizenz und wird auf <a href="https://github.com/zfhui/BerlinerChoere">GitHub</a> bereitgestellt.</p>
</div>

app/views/home/_marker_popup.html.erb
<% if user_signed_in? %>
  <div class="text-center">
    <%= link_to "Bearbeiten", edit_choir_path(choir) %>
  </div>
  </br>
<% end %>

<div class="marker-popup" style="min-width: 120px;">
  <% if choir.image? %>
    <div class="text-center">
      <img src="<%= choir.image_url(:marker).to_s %>"/>
    </div>
  </br>
  <% end %>
  <strong><%= choir.name %></strong>
  <address>
    <%= "#{choir.street_name} #{choir.house_no}"%></br>
    <%= "#{choir.zipcode} #{choir.city}"%>
  </address>
  <% if choir.website.present? %>
    <div class="text-right">
      <%= link_to choir.website, target: '_blank' do %>
        <span class="glyphicon glyphicon-globe"></span> Webseite
      <% end %>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<section id="map-section">
    <a name="map-section"></a>

    <!-- logo -->
    <div id="logo">
      <a href="<%= root_path %>">
      </a>
    </div>

    <!-- map -->
    <div id='map'></div>

    <!-- add choir button -->
    <div id="add-me">
      <a href="#add-me-section" class="btn btn-primary btn-round page-scroll">Dein Chor fehlt?</a></br>
      <span class="glyphicon glyphicon-chevron-down"></span>
    </div>
</section>

<!-- add choir form -->
<section id="add-me-section">
  <a name="add-me-section"></a>
  <div class="container">
    <h2>Deinen Chor zur Karte hinzufügen:</h2>
    <div id="add-me-form"></div>
    <div class="text-right" style="padding-top: 1.5em; padding-bottom: 1.5em;">
      <a href="#map-section" class="page-scroll"><span class="glyphicon glyphicon-map-marker"></span> Zur Karte</a>
    </div>
  </div>
</section>

<!-- about this page -->
<section id="about">
  <div class="container">
    <%= render partial: 'about' %>
    <div class="text-right" style="padding-top: 1.5em; padding-bottom: 1.5em;">
      <a href="#map-section" class="page-scroll"><span class="glyphicon glyphicon-map-marker"></span> Zur Karte</a>
    </div>
  </div>
  <a name="about"></a>
</section>

<!-- footer -->
<footer class="footer">
  <div class="container">
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to 'Login ', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
  <a name="footer"></a>
</footer>

<!-- JS -->
<script type="text/javascript">
$('#add-me-button').on('click', function(){
  $('#add-me-title').html("Deinen Chor zur Karte hinzufügen:");
  $('#add-me-form').html("<%= j render 'choirs/form', locals: {choir: @choir = Choir.new} %>");
});

$(document).ready(function(){
  showMap();
  $('#add-me-title').html("Deinen Chor zur Karte hinzufügen:");
  $('#add-me-form').html("<%= j render 'choirs/form', locals: {choir: @choir = Choir.new} %>");
});

function showMap(json) {
  var mapOptions = {
     maxZoom: 15,
     minZoom: 11,
     zoom: 11,
     markerZoomAnimation: true,
     zoomControl: false
  }

  var map = L.map('map', mapOptions).setView([52.520, 13.404], 11);

  var berlinMap = L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
      attribution: 'Map data &copy; <a href="http://openstreetmap.org" target="_blank">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com"  target="_blank">Mapbox</a>',
      maxZoom: 15,
      id: "<%= ENV['mapbox_map_id'] %>",
      accessToken: "<%= ENV['mapbox_auth_token'] %>"
  }).addTo(map);

  var mixedChoirMarkers = [];
  var womenChoirMarkers = [];
  var menChoirMarkers = [];
  var childrenChoirMarkers = [];
  var youthChoirMarkers = [];
  var elderlyChoirMarkers = [];
  var defaultChoirMarkers = [];

  <% @choirs.each do |choir| %>
    var marker = L.marker([<%= choir.latitude %>, <%= choir.longitude %>]).bindPopup('<%= j render( partial: 'marker_popup', locals: {choir: choir}) %>').addTo(map);

    var category = '<%= choir.category.name if choir.category.present? %>';
    switch (category) {
      case 'Gemischter Chor': mixedChoirMarkers.push(marker);
        break;
      case 'Frauenchor':      womenChoirMarkers.push(marker);
        break;
      case 'Männerchor':      menChoirMarkers.push(marker);
        break;
      case 'Kinderchor':      childrenChoirMarkers.push(marker);
        break;
      case 'Jugendchor':      youthChoirMarkers.push(marker);
        break;
      case 'Seniorenchor':    elderlyChoirMarkers.push(marker);
        break;
      default:                defaultChoirMarkers.push(marker);
    }
  <% end %>

  var mixedChoirs    = L.layerGroup(mixedChoirMarkers).addTo(map);
  var womenChoirs    = L.layerGroup(womenChoirMarkers).addTo(map);
  var menChoirs      = L.layerGroup(menChoirMarkers).addTo(map);
  var childrenChoirs = L.layerGroup(childrenChoirMarkers).addTo(map);
  var youthChoirs    = L.layerGroup(youthChoirMarkers).addTo(map);
  var elderlyChoirs  = L.layerGroup(elderlyChoirMarkers).addTo(map);
  var defaultChoirs  = L.layerGroup(defaultChoirMarkers).addTo(map);


  var choirCategories = {
    "Geschmicher Chor": mixedChoirs,
    "Frauenchor":       womenChoirs,
    "Männerchor":       menChoirs,
    "Kinderchor":       childrenChoirs,
    "Jugendchor":       youthChoirs,
    "Seniorenchor":     elderlyChoirs,
    "Sonstiger Chor":   defaultChoirs
  };

  L.control.layers({}, choirCategories).addTo(map);
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Berliner Chöre</title>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>

    <link rel="shortcut icon" href='<%=image_url("icons/favcon.png")%>' />
    <!-- webfonts---->
		<!-- <link href='http://fonts.googleapis.com/css?family=Crimson+Text:600,400,700' rel='stylesheet' type='text/css'> -->
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div class="container-fluid">
      <!-- notices and warnings -->
			<% if notice %>
				<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
				<p class="alert alert-danger"><%= alert %></p>
			<% end %>

      <%= yield %>
      <%= yield :javascript%>
    </div>

    <script type="text/javascript">
      logoResize();
    </script>
  </body>
</html>